spring:



  main:
    allow-circular-references: true
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:instaclone_auth
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


jwt:
  uri: /auth/**
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
service:
  username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
  password: ef919ae4-b893-4969-b782-57978180ad33











logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug



rate: '{cipher}8848f13bb98a3201de6cf5fe78c0a0928d2fe148be375fa4957105ece4f45382'
lanecount: 5000000000000
